const devilFruits = [];

const logia = [
    {
        name: "Plume-Plume Fruit",
        jname: "Moku-Moku no mi",
        element: "Element: Smoke",
        user: "User: Smoker",
        manga:"Manga Debut:  Chapter 100",
        anime:"Anime Debut: Episode 48",
    },
    {
        name: "Sand-Sand Fruit",
        jname: "Suna-Suna no mi",
        element : "Element: Sand",
        user: "User: Crocodile",
        manga:"Manga Debut: Chapter 127",
        anime:"Anime Debut: Episode 77"     
    },
    {
        name: "Flare-Flare Fruit",
        jname: "Mera-Mera no mi",
        element : "Element: Fire",
        user: "User: Sabo(Current), Portgas D.Ace(Deceased)",
        manga:"Manga Debut: Chapter 158",
        anime:"Anime Debut: Episode 94"
    },
    {
        name: "Rumble-Rumble Fruit",
        jname: "Goro-Goro no mi",
        element : "Element: Electricity",
        user: "User: Enel",
        manga:"Manga Debut: Chapter 241",
        anime:"Anime Debut: Episode 155"
    },
    {
        name: "Dark-Dark Fruit",
        jname: "Yami-Yami no mi",
        element : "Element: Darkness",
        user: "User: Marshall D.Teach",
        manga:"Manga Debut: Chapter 440",
        anime:"Anime Debut: Episode 325"
    },
    {
        name: "Chilly-Chilly Fruit",
        jname: "Hie-Hie no mi",
        element : "Element: Ice",
        user: "User: Kuzan(Aokiji)",
        manga:"Manga Debut: Chapter 303",
        anime:"Anime Debut: Episode 225"
    },
    {
        name: "Glint-Glint Fruit",
        jname: "Pika-Pika no mi",
        element : "Element: Light",
        user: "User: Borsalino(Kizaru)",
        manga:"Manga Debut: Chapter 506",
        anime:"Anime Debut: Episode 401"
    },
    {
        name: "Mag-Mag Fruit",
        jname: "Magu-Magu no mi",
        element : "Element: Magma",
        user: "User: Sakazuki(Akainu)",
        manga:"Manga Debut: Chapter 554",
        anime:"Anime Debut: Episode 463"
    },
    {
        name: "Swamp-Swamp Fruit",
        jname: "Numa-Numa no mi",
        element : "Element: Swamp",
        user: "User: Caribou",
        manga:"Manga Debut: Chapter 603",
        anime:"Anime Debut: Episode 521"
    },
    {
        name: "Gas-Gas Fruit",
        jname: "Gasu-Gasu no mi",
        element : "Element: Gas",
        user: "User: Caesar Clown",
        manga:"Manga Debut: Chapter 658",
        anime:"Anime Debut: Episode 582"
    },
    {
        name: "Snow-Snow Fruit",
        jname: "Yuki-Yuki no mi",
        element : "Element: Snow",
        user: "User: Monet(Deceased)",
        manga:"Manga Debut: Chapter 681",
        anime:"Anime Debut: Episode 607"
    },
    {
        name: "Forest-Forest Fruit",
        jname: "Mori-Mori no mi",
        element : "Element: Forest/Nature",
        user: "User: Aramaki(Ryokugyu)",
        manga:"Manga Debut: Chapter 1053",
        anime:"Anime Debut: Episode 1080"
    },
    {
        name: "Soot-Soot Fruit",
        jname: "Susu-Susu no mi",
        element : "Element: Soot",
        user: "User: Karasu",
        manga:"Manga Debut: Chapter 593",
        anime:"Anime Debut: Episode 510"
    },
    {
        name: "Jelly-Jelly Fruit",
        jname: "Toro-Toro no mi",
        element : "Element: Jelly (Unknown liquid)",
        user: "User: Honey Queen",
        manga:"Manga Debut: Non-canon",
        anime:"Anime Debut: Clockwork Island Adventure"
    },
    {
        name: "Paper-Paper Fruit",
        jname: "Pasa-Pasa no mi",
        element : "Element: Paper",
        user: "User: Simon",
        manga:"Manga Debut: Non-canon",
        anime:"Anime Debut: Big Secret Treasure of the Seven Phantom Islands"
    },
    {
        name: "Candy-Candy Fruit",
        jname: "Ame-Ame no mi",
        element : "Element: Liquid syrup",
        user: "User: Gasparde",
        manga:"Manga Debut: Non-canon",
        anime:"Anime Debut: Dead End Adventure"
    },  
];
const parBody = [
    {
        name: "Magnet-Magnet Fruit",
        jname: "Jiki-Jiki no mi",
        element : "Power: Magnetism",
        user: "User: Eustass kid",
        manga:"Manga Debut: Chapter 504",
        anime:"Anime Debut: Episode 398", 
        status:"(Awakened)" 
    },
    {
        name: "Chop-Chop Fruit",
        jname: "Bara-Bara no mi",
        element : "Power: Dismemberment",
        user: "User: Buggy",
        manga:"Manga Debut: Chapter 9",
        anime:"Anime Debut: Episode 4",   
    },
    {
        name: "Smooth-Smooth Fruit",
        jname: "Sube-Sube no mi",
        element : "Power: Smooth Body",
        user: "User: Alvida",
        manga:"Manga Debut: Chapter 2",
        anime:"Anime Debut: Episode 1",   
    },
    {
        name: "Bomb-Bomb Fruit",
        jname: "Bomu-Bomu no mi",
        element : "Power: Explosive Body parts",
        user: "User: Gem(Mr.5)",
        manga:"Manga Debut: Chapter 110",
        anime:"Anime Debut: Episode 65",   
    },
    {
        name: "Kilo-Kilo Fruit",
        jname: "Kiro-Kiro no mi",
        element : "Power: Change Body Weight(Kg)",
        user: "User: Mikita(Miss Valentine)",
        manga:"Manga Debut: Chapter 110",
        anime:"Anime Debut: Episode 65",   
    },
    {
        name: "Flower-Flower Fruit",
        jname: "Hana-Hana no mi",
        element : "Power: Create Body parts",
        user: "User: Nico Robin",
        manga:"Manga Debut: Chapter 114",
        anime:"Anime Debut: Episode 67",   
    },
    {
        name: "Munch-Munch Fruit",
        jname: "Baku-Baku no mi",
        element : "Power: Creates what he Eats",
        user: "User: Wapol",
        manga:"Manga Debut: Chapter 131",
        anime:"Anime Debut: Episode 79",   
    },
    {
        name: "Clone-Clone Fruit",
        jname: "Mane-Mane no mi",
        element : "Power: Imitation",
        user: "User: Bentham(Mr.2)(Current), Kurozumi Higurashi(Deceased)",
        manga:"Manga Debut: Chapter 129",
        anime:"Anime Debut: Episode 78",   
    },
    {
        name: "Dice-Dice Fruit",
        jname: "Supa-Supa no mi",
        element : "Power: Blades",
        user: "User: Daz Bonez(Mr.1)",
        manga:"Manga Debut: Chapter 160",
        anime:"Anime Debut: Episode 103",   
    },
    {
        name: "Spike-Spike Fruit",
        jname: "Toge-Toge no mi",
        element : "Power: Spikes",
        user: "User: Zala(Miss Doublefinger)",
        manga:"Manga Debut: Chapter 155",
        anime:"Anime Debut: Episode 103",   
    },
    {
        name: "Bind-Bind Fruit",
        jname: "Ori-Ori no mi",
        element : "Power: Cages",
        user: "User: Hina",
        manga:"Manga Debut: Chapter 217",
        anime:"Anime Debut: Episode 130",   
    },
    {
        name: "Spring-Spring Fruit",
        jname: "Bane-Bane no mi",
        element : "Power: Springs",
        user: "User: Bellamy",
        manga:"Manga Debut: Chapter 231",
        anime:"Anime Debut: Episode 150",   
    },
    {
        name: "Berry-Berry Fruit",
        jname: "Beri-Beri no mi",
        element : "Power: Body parts into berry-like balls",
        user: "User: Very Good",
        manga:"Manga Debut: Chapter 426",
        anime:"Anime Debut: Episode 309",   
    },
    {
        name: "Wheel-Wheel Fruit",
        jname: "Shari-Shari no mi",
        element : "Power: Arms & Legs into wheels",
        user: "User: Sharinguru",
        manga:"Manga Debut: Chapter 428",
        anime:"Anime Debut: N/A",   
    },
    {
        name: "Castle-Castle Fruit",
        jname: "Shiro-Shiro no mi",
        element : "Power: Living Fortress",
        user: "User: Capone Bege",
        manga:"Manga Debut: Chapter 508",
        anime:"Anime Debut: Episode 401",   
    },
    {
        name: "Tone-Tone Fruit",
        jname: "Oto-Oto no mi",
        element : "Power: Musical Instruments",
        user: "User: Scratchmen Apoo",
        manga:"Manga Debut: Chapter 509",
        anime:"Anime Debut: Episode 402",   
    },
    {
        name: "Hor-Hor Fruit",
        jname: "Horu-Horu no mi",
        element : "Power: Hormones",
        user: "User: Emporio Ivankov",
        manga:"Manga Debut: Chapter 537",
        anime:"Anime Debut: Episode 439", 
    },
    {
        name: "Shear-Shear Fruit",
        jname: "Choki-Choki no mi",
        element : "Power: Scissors",
        user: "User: Inazuma",
        manga:"Manga Debut: Chapter 540",
        anime:"Anime Debut: Episode 442", 
    },
    {
        name: "Twinkle-Twinkle Fruit",
        jname: "Kira-Kira no mi",
        element : "Power: Diamond",
        user: "User: Jozu",
        manga:"Manga Debut: Chapter 553",
        anime:"Anime Debut: Episode 463", 
    },
    {
        name: "Pocket-Pocket Fruit",
        jname: "Poke-Poke no mi",
        element : "Power: Pockets that store anything",
        user: "User: Blamenco",
        manga:"Manga Debut: Chapter 553",
        anime:"Anime Debut: Episode 461", 
    },
    {
        name: "Huge-Huge Fruit",
        jname: "Deka-Deka no mi",
        element : "Power: Enlarge",
        user: "User: Sanjuan wolf",
        manga:"Manga Debut: Chapter 575",
        anime:"Anime Debut: Episode 484", 
    },
    {
        name: "Arms-Arms Fruit",
        jname: "Buki-Buki no mi",
        element : "Power: Full Body Weapon",
        user: "User: Baby 5",
        manga:"Manga Debut: Chapter 682",
        anime:"Anime Debut: Episode 608", 
    },
    {
        name: "Spin-Spin Fruit",
        jname: "Guru-Guru no mi",
        element : "Power: Rotating",
        user: "User: Buffalo",
        manga:"Manga Debut: Chapter 692",
        anime:"Anime Debut: Episode 618", 
    },
    {
        name: "Jacket-Jacket Fruit",
        jname: "Jake-Jake no mi",
        element : "Power: Becomes a jacket",
        user: "User: Kelly Funk",
        manga:"Manga Debut: Chapter 715",
        anime:"Anime Debut: Episode 645", 
    },
    {
        name: "Pop-Pop Fruit",
        jname: "Pamu-Pamu no mi",
        element : "Power: Rupture",
        user: "User: Gladius",
        manga:"Manga Debut: Chapter 723",
        anime:"Anime Debut: Episode 653", 
    },
    {
        name: "Ton-Ton Fruit",
        jname: "Ton-Ton no mi",
        element : "Power: Change body weight(Tons)",
        user: "User: Machvise",
        manga:"Manga Debut: Chapter 735",
        anime:"Anime Debut: Episode 667", 
    },
    {
        name: "Ripple-Ripple Fruit",
        jname: "Hira-Hira no mi",
        element : "Power: Become flat and flexible",
        user: "User: Diamante",
        manga:"Manga Debut: Chapter 736",
        anime:"Anime Debut: Episode 668", 
    },
    {
        name: "Heat-Heat Fruit",
        jname: "Netsu-Netsu no mi",
        element : "Power: Heat",
        user: "User: Charlotte Oven",
        manga:"Manga Debut: Chapter 864",
        anime:"Anime Debut: Episode 827", 
    },
    {
        name: "Pile-Pile Fruit",
        jname: "Gocha-Gocha no mi",
        element : "Power: Merge themselves and others",
        user: "User: Charlotte Newshi",
        manga:"Manga Debut: Chapter 900",
        anime:"Anime Debut: Episode 875", 
    },
    {
        name: "Brain-Brain Fruit",
        jname: "Nomi-Nomi no mi",
        element : "Power: brain to expand indefinitely with new knowledge",
        user: "User: VegaPunk",
        manga:"Manga Debut: Chapter 1066",
        anime:"Anime Debut: N/A", 
    },
    {
        name: "Isle-Isle Fruit",
        jname: "Shima-Shima no mi",
        element : "Power: Merge with an island's environment and manipulate it",
        user: "User: Avalo Pizarro",
        manga:"Manga Debut: Chapter 1080",
        anime:"Anime Debut: N/A", 
    },
    {
        name: "(Unknown) Fruit",
        jname: "Kachi-Kachi no mi",
        element : "Power: Harden body and heat up",
        user: "User: Bear King",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film:Clockwork Island Adventure",   
    },
    {
        name: "Mini-Mini Fruit",
        jname: "Mini-Mini no mi",
        element : "Power: Miniature",
        user: "User: Lily Enstomach(Anime), Blyue(Game)",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Episode 575",   
    },
    {
        name: "Hot-Hot Fruit",
        jname: "Atsu-Atsu no mi",
        element : "Power: Hot",
        user: "User: Don Accino",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Episode 326",   
    },
    {
        name: "Net-Net Fruit",
        jname: "Ami-Ami no mi",
        element : "Power: Net",
        user: "User: Largo",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Episode 427",   
    },
    {
        name: "Smelt-Smelt Fruit",
        jname: "Gutsu-Gutsu no mi",
        element : "Power: body into blast furnace",
        user: "User: Bill",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Episode 746",   
    },
    {
        name: "Roll-Roll Fruit",
        jname: "Koro-Koro no mi",
        element : "Power: Hands and feet into wheels",
        user: "User: Averyon(Deceased?)",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Episode 747",   
    },
];
const parSub = [
    {
        name: "Wax-Wax Fruit",
        jname: "Doru-Doru no mi",
        element : "Power: Wax",
        user: "User: Galdino(Mr.3)",
        manga:"Manga Debut: Chapter 117",
        anime:"Anime Debut: Episode 70",   
    },
    {
        name: "String-String Fruit",
        jname: "Ito-Ito no mi",
        element : "Power: String",
        user: "User: Donquixote Doflamingo",
        manga:"Manga Debut: Chapter 234",
        anime:"Anime Debut: Episode 151",
        status:"(Awakened)"   
    },
    {
        name: "Bubble-Bubble Fruit",
        jname: "Awa-Awa no mi",
        element : "Power: Bubbles",
        user: "User: Kalifa",
        manga:"Manga Debut: Chapter 408",
        anime:"Anime Debut: Episode 293",   
    },
    {
        name: "Straw-Straw Fruit",
        jname: "Wara-Wara no mi",
        element : "Power: Straw",
        user: "User: Basil Hawkins(Deceased)",
        manga:"Manga Debut: Chapter 508",
        anime:"Anime Debut: Episode 401", 
    },
    {
        name: "Venom-Venom Fruit",
        jname: "Doku-Doku no mi",
        element : "Power: Poison",
        user: "User: Magellan",
        manga:"Manga Debut: Chapter 528",
        anime:"Anime Debut: Episode 425", 
    },
    {
        name: "Garb-Garb Fruit",
        jname: "Fuku-Fuku no mi",
        element : "Power: Clothing",
        user: "User: Kin'emon",
        manga:"Manga Debut: Chapter 663",
        anime:"Anime Debut: Episode 588", 
    },
    {
        name: "Barrier-Barrier Fruit",
        jname: "Bari-Bari no mi",
        element : "Power: barriers",
        user: "User: Bartolomeo(Current), Kurozumi Senimaru(Deceased)",
        manga:"Manga Debut: Chapter 708",
        anime:"Anime Debut: Episode 637", 
    },
    {
        name: "Stick-Stick Fruit",
        jname: "Beta-Beta no mi",
        element : "Power: Mucus",
        user: "User: Trebol",
        manga:"Manga Debut: Chapter 700",
        anime:"Anime Debut: Episode 629", 
    },
    {
        name: "Lick-Lick Fruit",
        jname: "Pero-Pero no mi",
        element : "Power: Candy",
        user: "User: Charlotte Perospero",
        manga:"Manga Debut: Chapter 834",
        anime:"Anime Debut: Episode 795", 
    },
    {
        name: "Bis-Bis Fruit",
        jname: "Bisu-Bisu no mi",
        element : "Power: Biscuits",
        user: "User: Charlotte Cracker",
        manga:"Manga Debut: Chapter 835",
        anime:"Anime Debut: Episode 796", 
    },
    {
        name: "Butter-Butter Fruit",
        jname: "Bata-Bata no mi",
        element : "Power: Butter",
        user: "User: Charlotte Galette",
        manga:"Manga Debut: Chapter 846",
        anime:"Anime Debut: Episode 811", 
    },
    {
        name: "Cream-Cream Fruit",
        jname: "Kuri-Kuri no mi",
        element : "Power: Cream",
        user: "User: Charlotte Opera",
        manga:"Manga Debut: Chapter 846",
        anime:"Anime Debut: Episode 810", 
    },
    {
        name: "Mochi-Mochi Fruit",
        jname: "Mochi-Mochi no mi",
        element : "Power: Mochi",
        user: "User: Charlotte Katakuri",
        manga:"Manga Debut: Chapter 863",
        anime:"Anime Debut: Episode 833",
        status:"(Awakened)",
        type:"(Special Paramecia)"
    },
    {
        name: "Glorp-Glorp Fruit(Unknown Type)",
        jname: "Gunyo-Gunyo no mi",
        element : "Power: Clay",
        user: "User: Prince Grus",
        manga:"Manga Debut: Chapter 966",
        anime:"Anime Debut: N/A", 
    },
    {
        name: "Brush-Brush Fruit",
        jname: "Fude-Fude no mi",
        element : "Power: Ink",
        user: "User: Kurozumi Kanjuro(Deceased)",
        manga:"Manga Debut: Chapter 754",
        anime:"Anime Debut: Episode 691", 
    },
    {
        name: "Shroom-Shroom Fruit",
        jname: "Noko-Noko no mi",
        element : "Power: Mushroom",
        user: "User: Musshuru",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Bloom in Winter, Miracle Sakura",   
    },
    {
        name: "Chain-Chain Fruit",
        jname: "Jara-Jara no mi",
        element : "Power: Chain",
        user: "User: Mad Treasure",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film:Heart of Gold",   
    },
    {
        name: "Gold-Gold Fruit",
        jname: "Goru-Goru no mi",
        element : "Power: Gold",
        user: "User: Gild Tesoro",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film: Gold",   
    },
];
const parEnv = [
    {
        name: "Slow-Slow Fruit",
        jname: "Noro-Noro no mi",
        element : "Power: Slows targets",
        user: "User: Foxy",
        manga:"Manga Debut: Chapter 308",
        anime:"Anime Debut: Episode 210",   
    },
    {
        name: "Door-Door Fruit",
        jname: "Doa-Doa no mi",
        element : "Power: Creates Doors",
        user: "User: Blueno",
        manga:"Manga Debut: Chapter 326",
        anime:"Anime Debut: Episode 231",   
    },
    {
        name: "Op-Op Fruit",
        jname: "Ope-Ope no mi",
        element : "Power: Operation",
        user: "User: Trafalgar D.Waterlaw",
        manga:"Manga Debut: Chapter 504",
        anime:"Anime Debut: Episode 398",
        status:"(Awakened)" 
    },
    {
        name: "Press-Press Fruit",
        jname: "Zushi-Zushi no mi",
        element : "Power: Gravitational force",
        user: "User: Issho(Fujitora)",
        manga:"Manga Debut: Chapter 701",
        anime:"Anime Debut: Episode 631", 
    },
    {
        name: "Art-Art Fruit",
        jname: "Ato-Ato no mi",
        element : "Power: Turn things into abstract art",
        user: "User: Grolla",
        manga:"Manga Debut: Chapter 714",
        anime:"Anime Debut: Episode 635", 
    },
    {
        name: "Swim-Swim Fruit",
        jname: "Sui-Sui no mi",
        element : "Power: Swim anywhere",
        user: "User: Senor Pink(Current), S-Shark(Artificial)",
        manga:"Manga Debut: Chapter 732",
        anime:"Anime Debut: Episode 664", 
    },
    {
        name: "Stone-Stone Fruit",
        jname: "Ishi-Ishi no mi",
        element : "Power: Merge and manipulate stone",
        user: "User: Pica",
        manga:"Manga Debut: Chapter 736",
        anime:"Anime Debut: Episode 669", 
    },
    {
        name: "Mirror-Mirror Fruit",
        jname: "Mira-Mira no mi",
        element : "Power: Control Mirrors, pocket dimension",
        user: "User: Charlotte Brulee",
        manga:"Manga Debut: Chapter 831",
        anime:"Anime Debut: Episode 790", 
    },
    {
        name: "Book-Book Fruit",
        jname: "Buku-Buku no mi",
        element : "Power: Control Books, pocket dimension",
        user: "User: Charlotte Mont-d'or",
        manga:"Manga Debut: Chapter 846",
        anime:"Anime Debut: Episode 810", 
    },
    {
        name: "Cook-Cook Fruit",
        jname: "Kuku-Kuku no mi",
        element : "Power: Objects into food",
        user: "User: Streusen",
        manga:"Manga Debut: Chapter 868",
        anime:"Anime Debut: Episode 832", 
    },
    {
        name: "Push-Push Fruit",
        jname: "Oshi-Oshi no mi",
        element : "Power: Make the ground malleable",
        user: "User: Morley",
        manga:"Manga Debut: Chapter 904",
        anime:"Anime Debut: Episode 880", 
    },
    {
        name: "Ripe-Ripe Fruit",
        jname: "Juku-Juku no mi",
        element : "Power: Mature/Decay",
        user: "User: Shinobu",
        manga:"Manga Debut: Chapter 924",
        anime:"Anime Debut: Episode 916", 
    },
    {
        name: "Sick-Sick Fruit",
        jname: "Shiku-Shiku no mi",
        element : "Power: Afflict others with dieases",
        user: "User: Doc Q",
        manga:"Manga Debut: Chapter 1063",
        anime:"Anime Debut: N/A", 
    },
    {
        name: "Tremor-Tremor Fruit",
        jname: "Gura-Gura no mi",
        element : "Power: EarthQuakes",
        user: "User: Marshall D.Teach(Current), Edward Newgate(Deceased)",
        manga:"Manga Debut: Chapter 552",
        anime:"Anime Debut: Episode 461", 
    },
    {
        name: "Calm-Calm Fruit",
        jname: "Nagi-Nagi no mi",
        element : "Power: Sound Proof fields",
        user: "User: Donquixote Rosinante",
        manga:"Manga Debut: Chapter 764",
        anime:"Anime Debut: Episode 703", 
    },
    {
        name: "Grow-Grow Fruit",
        jname: "Mosa-Mosa no mi",
        element : "Power: Ability to accelerate plant growth",
        user: "User: Binz",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film: Z",   
    },
    {
        name: "More-More Fruit",
        jname: "Moa-Moa no mi",
        element : "Power: Amplify Size and Speed of object",
        user: "User: Byrnndi World",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film:: 3D2Y",   
    },
    {
        name: "Cube-Cube Fruit",
        jname: "Kyubu-Kyubu no mi",
        element : "Power: Turn things into Cubes",
        user: "User: Gairam",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film:: 3D2Y",   
    },
    {
        name: "Through-Through Fruit",
        jname: "Nuke-Nuke no mi",
        element : "Power: Phase through objects",
        user: "User: Tanaka",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film: Z",   
    },
    {
        name: "Clank-Clank Fruit",
        jname: "Gasha-Gasha no mi",
        element : "Power: Reassemble and dismantle objects",
        user: "User: Douglas Bullet",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film: Stampede",   
    },
    {
        name: "Sing-Sing Fruit",
        jname: "Uta-Uta no mi",
        element : "Power: Consciousnesses into a virtual space by singing",
        user: "User: Uta",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film: Red",   
    },
    {
        name: "Grab-Grab Fruit",
        jname: "Kote-Kote no mi",
        element : "Power: large gauntlets that manipulate things",
        user: "User: Adio Suerte",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece game: Odyssey",   
    },
    {
        name: "(Unknown) Fruit",
        jname: "Kyara-Kyara no mi",
        element : "Power: Consciousness to non-living souls",
        user: "User: Lip Shark",
        manga:"Manga Debut: Fischer's x One Piece: Chapter 9",
        anime:"Anime Debut: Non-Canon",   
    },
    {
        name: "Game-Game Fruit",
        jname: "Gemu-Gemu no mi",
        element : "Power: Game-World",
        user: "User: Dama's Tablet",
        manga:"Manga Debut: Fischer's x One Piece: Chapter 4",
        anime:"Anime Debut: Non-Canon",   
    },
];
const parPow = [
    {
        name: "Hallow-Hallow Fruit",
        jname: "Horo-Horo no mi",
        element : "Power: Conjure ghosts",
        user: "User: Perona",
        manga:"Manga Debut: Chapter 442",
        anime:"Anime Debut: Episode 337",   
    },
    {
        name: "Time-Time Fruit",
        jname: "Toki-Toki no mi",
        element : "Power: Time Travel",
        user: "User: Kozuki Toki(Deceased)",
        manga:"Manga Debut: Chapter 920",
        anime:"Anime Debut: Episode 910", 
    },
    {
        name: "Ride-Ride Fruit",
        jname: "Nori-Nori no mi",
        element : "Power: Command anything she rides on",
        user: "User: Kujaku",
        manga:"Manga Debut: Chapter 1094",
        anime:"Anime Debut: N/A", 
    },
    {
        name: "Warp-Warp Fruit",
        jname: "Wapu-Wapu no mi",
        element : "Power: Teleportation",
        user: "User: Van Augur",
        manga:"Manga Debut: Chapter 1063",
        anime:"Anime Debut: N/A", 
    },
    {
        name: "Whip-Whip Fruit",
        jname: "Muchi-Muchi no mi",
        element : "Power: Command",
        user: "User: Kujaku",
        manga:"Manga Debut: Chapter 1080",
        anime:"Anime Debut: N/A", 
    },
    {
        name: "Wring-Wring Fruit",
        jname: "Shibo-Shibo no mi",
        element : "Power: Drain liquids from things",
        user: "User: Charlotte Smoothie",
        manga:"Manga Debut: Chapter 846",
        anime:"Anime Debut: Episode 812", 
    },
    {
        name: "Pump-Pump Fruit",
        jname: "Kobu-Kobu no mi",
        element : "Power: Encouragement",
        user: "User: Belo Betty",
        manga:"Manga Debut: Chapter 904",
        anime:"Anime Debut: Episode 880", 
    },
    {
        name: "Memo-Memo Fruit",
        jname: "Memo-Memo no mi",
        element : "Power: Manipulate Memories",
        user: "User: Charlotte Pudding",
        manga:"Manga Debut: Chapter 851",
        anime:"Anime Debut: Episode 818", 
    },
    {
        name: "Heal-Heal Fruit",
        jname: "Chiyu-Chiyu no mi",
        element : "Power: Healing",
        user: "User: Mansherry",
        manga:"Manga Debut: Chapter 774",
        anime:"Anime Debut: Episode 714", 
    },
    {
        name: "Stitch-Stitch Fruit",
        jname: "Nui-Nui no mi",
        element : "Power: stitch things together",
        user: "User: Issho(Fujitora)",
        manga:"Manga Debut: Chapter 711",
        anime:"Anime Debut: Episode 641", 
    },
    {
        name: "Glare-Glare Fruit",
        jname: "Giro-Giro no mi",
        element : "Power: See through things and read minds",
        user: "User: Viola",
        manga:"Manga Debut: Chapter 712",
        anime:"Anime Debut: Episode 640", 
    },
    {
        name: "Love-Love Fruit",
        jname: "Mero-Mero no mi",
        element : "Power: Fall in love",
        user: "User: Boa Hancock(Current), S-Snake(Artificial)",
        manga:"Manga Debut: Chapter 516",
        anime:"Anime Debut: Episode 410",   
    },
    {
        name: "Wash-Wash Fruit",
        jname: "Woshu-Woshu no mi",
        element : "Power: Wash and hang things",
        user: "User: Tsuru",
        manga:"Manga Debut: Chapter 556",
        anime:"Anime Debut: Episode 465", 
    },
    {
        name: "Float-Float Fruit",
        jname: "Fuwa-Fuwa no mi",
        element : "Power: Levitation",
        user: "User: Shiki",
        manga:"Manga Debut: Chapter 0",
        anime:"Anime Debut: Episode 426", 
    },
    {
        name: "Mark-Mark Fruit",
        jname: "Mato-Mato no mi",
        element : "Power: Homeing",
        user: "User: Vander Decken IX",
        manga:"Manga Debut: Chapter 613",
        anime:"Anime Debut: Episode 532", 
    },
    {
        name: "Soul-Soul Fruit",
        jname: "Soru-Soru no mi",
        element : "Power: Interact & Manipulate Souls",
        user: "User: Big Mom(Deceased?), Carmel(Deceased)",
        manga:"Manga Debut: Chapter 651",
        anime:"Anime Debut: Episode 571", 
    },
    {
        name: "Hobby-Hobby Fruit",
        jname: "Hobi-Hobi no mi",
        element : "Power: People into toys, erase existence",
        user: "User: Sugar",
        manga:"Manga Debut: Chapter 701",
        anime:"Anime Debut: Episode 630", 
    },
    {
        name: "Shadow-Shadow Fruit",
        jname: "Kage-Kage no mi",
        element : "Power: Manifest & Control shadows",
        user: "User: Gecko Moria",
        manga:"Manga Debut: Chapter 443",
        anime:"Anime Debut: Episode 338",   
    },
    {
        name: "Scroll-Scroll Fruit",
        jname: "Maki-Maki no mi",
        element : "Power: Scrolls",
        user: "User: Raizo",
        manga:"Manga Debut: Chapter 817",
        anime:"Anime Debut: Episode 768", 
    },
    {
        name: "Rust-Rust Fruit",
        jname: "Sabi-Sabi no mi",
        element : "Power: Rust",
        user: "User: Shu",
        manga:"Manga Debut: Chapter 426",
        anime:"Anime Debut: Episode 309",   
    },
    {
        name: "Clear-Clear Fruit",
        jname: "Suke-Suke no mi",
        element : "Power: Invisibility",
        user: "User: Shiryu(Current), Absalom(Deceased)",
        manga:"Manga Debut: Chapter 444",
        anime:"Anime Debut: Episode 339", 
    },
    {
        name: "Strong-Strong Fruit",
        jname: "Riki-Riki no mi",
        element : "Power: Strength",
        user: "User: Jesus Burgess",
        manga:"Manga Debut: Chapter 1063",
        anime:"Anime Debut: N/A", 
    },
    {
        name: "Glug-Glug Fruit",
        jname: "Gabu-Gabu no mi",
        element : "Power: Liquor",
        user: "User: Vasco Shot",
        manga:"Manga Debut: Chapter 1080",
        anime:"Anime Debut: N/A", 
    },
    {
        name: "Millet-Millet Fruit",
        jname: "Kibi-Kibi no mi",
        element : "Power: Tame animals with the dango from her cheeks",
        user: "User: Otama",
        manga:"Manga Debut: Chapter 911",
        anime:"Anime Debut: Episode 893", 
    },
    {
        name: "Revive-Revive Fruit",
        jname: "Yomi-Yomi no mi",
        element : "Power: Resurrection",
        user: "User: Brook",
        manga:"Manga Debut: Chapter 442",
        anime:"Anime Debut: Episode 337",   
    },
    {
        name: "Damage-Damage Fruit",
        jname: "Sonshō-Sonshō no mi(Unknown)",
        element : "Power: Damage to power",
        user: "User: Urouge",
        manga:"Manga Debut: Chapter 498",
        anime:"Anime Debut: Episode 392",   
    },
    {
        name: "Puff-Puff Fruit",
        jname: "Hoya-Hoya no mi",
        element : "Power: Becomes genie lamp, summons genie",
        user: "User: Charlotte Daifuku",
        manga:"Manga Debut: Chapter 846",
        anime:"Anime Debut: Episode 826", 
    },
    {
        name: "Paw-Paw Fruit",
        jname: "Nikyu-Nikyu no mi",
        element : "Power: Repel things he touches",
        user: "User: Bartholomew Kuma(Deceased?) S-Bear(Artificial)",
        manga:"Manga Debut: Chapter 443",
        anime:"Anime Debut: Episode 338",
    },
    {
        name: "Age-Age Fruit",
        jname: "Fuke-Fuke no mi(Unknown)",
        element : "Power: Ages people she touches",
        user: "User: Jewelry Bonney",
        manga:"Manga Debut: Chapter 498",
        anime:"Anime Debut: Episode 392",   
    },
    {
        name: "Pet-Pet Fruit",
        jname: "Peto-Peto no mi",
        element : "Power: Control living creature",
        user: "User: Breed",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Episode 625",   
    },
    {
        name: "(Unknown) Fruit",
        jname: "Peke-Peke no mi",
        element : "Power: Transform other people into clones of Peketan",
        user: "User: Peketan",
        manga:"Manga Debut: Fischer's x One Piece: Chapter 2",
        anime:"Anime Debut: Non-Canon",   
    },
    {
        name: "Color-Color Fruit",
        jname: "Iro-Iro no mi",
        element : "Power: Creates paint to camouflage",
        user: "User: Psycho P",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film: Heart of Gold",   
    },
    {
        name: "Luck-Luck Fruit",
        jname: "Raki-Raki no mi",
        element : "Power: Steals peoples luck",
        user: "User: Baccarat",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film: Heart of Gold",   
    },
    {
        name: "Viso-Viso Fruit",
        jname: "Bijo-Bijo no mi",
        element : "Power: Creates Illusion",
        user: "User: Ann",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film: Stampede",   
    },
    {
        name: "Return-Return Fruit",
        jname: "Modo-Modo no mi",
        element : "Power: Twelve years younger",
        user: "User: Ain",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Film: Z",   
    },
    {
        name: "Copy-Copy Fruit(Unknown)",
        jname: "Kopi-Kopi no mi",
        element : "Power: Copy others abilities",
        user: "User: Chameleone",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece Premier Show",   
    },
    {
        name: "Goe-Goe Fruit",
        jname: "Goe-Goe no mi",
        element : "Power: Energy Beams by shouting",
        user: "User: Eldoraggo",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece: The Movie",   
    },
    {
        name: "Whisper-Whisper Fruit",
        jname: "Hiso-Hiso no mi",
        element : "Power: Speak telepathically to animals",
        user: "User: Apis",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Episode 54",   
    },
    {
        name: "Sickle-Sickle Fruit",
        jname: "Kama-Kama no mi",
        element : "Power: Slicing air blades",
        user: "User: Apis",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Episode 56",   
    },
    {
        name: "Sleep-Sleep Fruit",
        jname: "Nemu-Nemu no mi",
        element : "Power: fall asleep",
        user: "User: Noko",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Episode 220",   
    },
];
const zoanNormal = [
    {
        name: "Human-Human Fruit",
        jname: "Hito-Hito no mi",
        element : "Model: Human",
        user: "User: Tony-Tony Chopper",
        manga:"Manga Debut: Chapter 134",
        anime:"Anime Debut: Episode 81",   
    },
    {
        name: "Ox-Ox Fruit: Bison",
        jname: "Ushi-Ushi no mi",
        element: "Model: Bison",
        user: "User: Dalton",
        manga:"Manga Debut:  Chapter 132",
        anime:"Anime Debut: Episode 79",
    },
    {
        name: "Ox-Ox Fruit: Giraffe",
        jname: "Ushi-Ushi no mi",
        element : "Model: Giraffe",
        user: "User: Kaku",
        manga:"Manga Debut: Chapter 323",
        anime:"Anime Debut: Episode 230",
        Status: "(Awakened)"
    },
    {
        name: "Ox-Ox Fruit: Minotaur",
        jname: "Ushi-Ushi no mi",
        element : "Model: Minotaur",
        user: "User: Minotaurus",
        manga:"Manga Debut: 525",
        anime:"Anime Debut: 422",
        Status: "(Awakened)"
    },
    {
        name: "Ox-Ox Fruit: Alpaca",
        jname: "Ushi-Ushi no mi(Unknown)",
        element : "Model: Alpaca",
        user: "User: Alpacachino(Object: Canon)",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: 575"
    },
    {
        name: "Tweet-Tweet Fruit: Falcon",
        jname: "Tori-Tori no mi",
        element : "Model: Falcon",
        user: "User: Pell",
        manga:"Manga Debut: Chapter 155",
        anime:"Anime Debut: Episode 91"
    },
    {
        name: "Tweet-Tweet Fruit: Albatross",
        jname: "Tori-Tori no mi",
        element : "Model: Albatross",
        user: "User: Morgans",
        manga:"Manga Debut: Chapter 860",
        anime:"Anime Debut: Episode 828"
    },
    {
        name: "Tweet-Tweet Fruit: Eagle",
        jname: "Tori-Tori no mi",
        element : "Model: Eagle",
        user: "User: Bazu",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: One Piece 3D: Straw Hat Chase"
    },
    {
        name: "Dog-Dog Fruit: Dachshund",
        jname: "Inu-Inu no mi",
        element : "Model: Dachshund",
        user: "User: Lasso(Object: Gun)",
        manga:"Manga Debut: Chapter 160",
        anime:"Anime Debut: Episode 103"
    },
    {
        name: "Dog-Dog Fruit: Tanuki",
        jname: "Inu-Inu no mi",
        element : "Model: Tanuki",
        user: "User: Bunbuku-Kun(Object: Teapot)",
        manga:"Manga Debut: Chapter 911",
        anime:"Anime Debut: Episode 894"
    },
    {
        name: "Dog-Dog Fruit: Jackal",
        jname: "Inu-Inu no mi",
        element : "Model: Jackal",
        user: "User: Chaka",
        manga:"Manga Debut: Chapter 155",
        anime:"Anime Debut: Episode 91"
    },
    {
        name: "Dog-Dog Fruit: Wolf",
        jname: "Inu-Inu no mi",
        element : "Model: Wolf",
        user: "User: Jabra",
        manga:"Manga Debut: Chapter 375",
        anime:"Anime Debut: Episode 264"
    },
    {
        name: "Dog-Dog Fruit: Chihuahua",
        jname: "Inu-Inu no mi",
        element : "Model: Chihuahua",
        user: "User: Minochihuahua",
        manga:"Manga Debut: 662(Cover)",
        anime:"Anime Debut: N/A",
        Status: "(Unknown)"
    },
    {
        name: "Dog-Dog Fruit: Dalmation",
        jname: "Inu-Inu no mi",
        element : "Model: Dalmation",
        user: "User: Dalmatian",
        manga:"Manga Debut: Chapter 553",
        anime:"Anime Debut: Episode 462"
    },
    {
        name: "Horse-Horse Fruit: Horse",
        jname: "Uma-Uma no mi",
        element : "Model: Horse",
        user: "User: Pierre",
        manga:"Manga Debut: Chapter 237",
        anime:"Anime Debut: Episode 153"
    },
    {
        name: "Horse-Horse Fruit: Zebra",
        jname: "Uma-Uma no mi",
        element : "Model: Zebra",
        user: "User: Minozebra",
        manga:"Manga Debut: 533",
        anime:"Anime Debut: 434",
        Status: "(Awakened)"
    },
    {
        name: "Snake-Snake Fruit: King Cobra",
        jname: "Hebi-Hebi no mi",
        element : "Model: King Cobra",
        user: "User: Boa Marigold",
        manga:"Manga Debut: Chapter 516",
        anime:"Anime Debut: Episode 409"
    },
    {
        name: "Snake-Snake Fruit: Anaconda",
        jname: "Hebi-Hebi no mi",
        element : "Model: Anaconda",
        user: "User: Boa Sandersonia",
        manga:"Manga Debut: Chapter 516",
        anime:"Anime Debut: Episode 409"
    },
    {
        name: "Bug-Bug Fruit: Caterpillar",
        jname: "Mushi-Mushi no mi(Unknown)",
        element : "Model: Caterpillar",
        user: "User: Epoida",
        manga:"Manga Debut: Chapter 553",
        anime:"Anime Debut: Episode 467"
    },
    {
        name: "Bug-Bug Fruit: Rhino Beetle",
        jname: "Mushi-Mushi no mi",
        element : "Model: Rhino Beetle",
        user: "User: Kabu",
        manga:"Manga Debut: Chapter 710",
        anime:"Anime Debut: Episode 640"
    },
    {
        name: "Bug-Bug Fruit: Hornet",
        jname: "Mushi-Mushi no mi",
        element : "Model: Hornet",
        user: "User: Bian",
        manga:"Manga Debut: Chapter 717",
        anime:"Anime Debut: Episode 647"
    },
    {
        name: "Cat-Cat Fruit: Leopard",
        jname: "Neko-Neko no mi",
        element : "Model: Leopard",
        user: "User: Rob Lucci",
        manga:"Manga Debut: Chapter 323",
        anime:"Anime Debut: Episode 230",
        Status:"(Awakened)"
    },
    {
        name: "Cat-Cat Fruit: Cheetah",
        jname: "Neko-Neko no mi(Unknown)",
        element : "Model: Cheetah",
        user: "User: Chiqicheetah",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Episode 213",
    },
    {
        name: "Elephant-Elephant Fruit",
        jname: "Zou-Zou no mi",
        element : "Model: Elephant(Object: Sword)",
        user: "User: Funkfreed",
        manga:"Manga Debut: Chapter 365",
        anime:"Anime Debut: Episode 254"
    },
    {
        name: "Spider-Spider Fruit: Spider",
        jname: "Kumo-Kumo no mi(Unknown)",
        element : "Model: Spider",
        user: "User: Onigumo",
        manga:"Manga Debut: Chapter 420",
        anime:"Anime Debut: Episode 302"
    },
    {
        name: "Mole-Mole Fruit",
        jname: "Mogu-Mogu no mi",
        element : "Model: Mole",
        user: "User: Drophy",
        manga:"Manga Debut: Chapter 160",
        anime:"Anime Debut: Episode 103"
    },

    {
        name: "Koala-Koala Fruit",
        jname: "Koara-Koara no mi(Unknown)",
        element : "Model: Koala",
        user: "User: MinoKoala",
        manga:"Manga Debut: 531",
        anime:"Anime Debut: 432",
        Status: "(Awakened)"
    },
    {
        name: "Rhino-Rhino Fruit",
        jname: "Sai-Sai no mi(Unknown)",
        element : "Model: Rhinoceros",
        user: "User: Minorhinoceros",
        manga:"Manga Debut: 532",
        anime:"Anime Debut: 433",
        Status: "(Awakened)"
    },
    {
        name: "Turtle-Turtle Fruit",
        jname: "Kame-Kame no mi",
        element : "Model: Turtle",
        user: "User: Pekoms",
        manga:"Manga Debut: Chapter 651",
        anime:"Anime Debut: Episode 570"
    },
    {
        name: "Egg-Egg Fruit",
        jname: "Tama-Tama no mi",
        element : "Model: Egg",
        user: "User: Tamago",
        manga:"Manga Debut: Chapter 651",
        anime:"Anime Debut: Episode 570"
    },

    {
        name: "Sala-Sala Fruit",
        jname: "Sara-Sara no mi",
        element : "Model: Axolotl",
        user: "User: Smiley(Deceased)",
        manga:"Manga Debut: Chapter 668",
        anime:"Anime Debut: Episode 594"
    },
];
const zoanAnicent = [
    {
        name: "Dragon-Dragon Fruit: Allosaurus",
        jname: "Ryu-Ryu no mi",
        element : "Model: Allosaurus",
        user: "User: X. Drake",
        manga:"Manga Debut: Chapter 498",
        anime:"Anime Debut: Episode 392",
        Type:"(Ancient Zoan)"  
    },
    {
        name: "Dragon-Dragon Fruit: Spinosaurus",
        jname: "Ryu-Ryu no mi",
        element : "Model: Spinosaurus",
        user: "User: Page One",
        manga:"Manga Debut: Chapter 929",
        anime:"Anime Debut: Episode 923",
        Type:"(Ancient Zoan)"  
    },
    {
        name: "Dragon-Dragon Fruit: Pteranodon",
        jname: "Ryu-Ryu no mi",
        element : "Model: Pteranodon",
        user: "User: King",
        manga:"Manga Debut: Chapter 925",
        anime:"Anime Debut: Episode 918",
        Type:"(Ancient Zoan)"  
    },
    {
        name: "Dragon-Dragon Fruit: Brachiosaurus",
        jname: "Ryu-Ryu no mi",
        element : "Model: Brachiosaurus",
        user: "User: Queen",
        manga:"Manga Debut: Chapter 925",
        anime:"Anime Debut: Episode 918",
        Type:"(Ancient Zoan)"  
    },
    {
        name: "Dragon-Dragon Fruit: Pachycephalosaurus",
        jname: "Ryu-Ryu no mi",
        element : "Model: Pachycephalosaurus",
        user: "User: Ulti",
        manga:"Manga Debut: Chapter 977",
        anime:"Anime Debut: Episode 982",
        Type:"(Ancient Zoan)"  
    },
    {
        name: "Dragon-Dragon Fruit: Triceratops",
        jname: "Ryu-Ryu no mi",
        element : "Model: Triceratops",
        user: "User: Sasaki",
        manga:"Manga Debut: Chapter 977",
        anime:"Anime Debut: Episode 982",
        Type:"(Ancient Zoan)"  
    },
    {
        name: "Spider-Spider Fruit: Rosamygale Grauvogeli",
        jname: "Kumo-Kumo no Mi",
        element : "Model: Rosamygale Grauvogeli",
        user: "User: Black Maria",
        manga:"Manga Debut: Chapter 977",
        anime:"Anime Debut: Episode 982",
        Type:"(Ancient Zoan)"  
    },
    {
        name: "Cat-Cat Fruit: Saber Tiger",
        jname: "Neko-Neko no Mi",
        element : "Model: Spider Tiger",
        user: "User: Who's-Who",
        manga:"Manga Debut: Chapter 977",
        anime:"Anime Debut: Episode 982",
        Type:"(Ancient Zoan)"  
    },
    {
        name: "Elephant-Elephant Fruit: Mammoth",
        jname: "Zou-Zou no mi",
        element : "Model: Mammoth",
        user: "User: Jack",
        manga:"Manga Debut: Chapter 801",
        anime:"Anime Debut: Episode 746"
    },
];
const zoanMythical = [
    {
        name: "Human-Human no mi: Nika",
        jname: "Hito-Hito no mi",
        element : "Model: Nika",
        user: "User: Monkey D.Luffy",
        manga:"Manga Debut: Chapter 1",
        anime:"Anime Debut: Episode 1",
        Status: "(Awakened)",
        Type:"(Mythical Zoan)"  
    },
    {
        name: "Human-Human no mi: Buddha",
        jname: "Hito-Hito no mi",
        element : "Model: Buddha",
        user: "User: Sengoku",
        manga:"Manga Debut: Chapter 234",
        anime:"Anime Debut: Episode 151",
        Type:"(Mythical Zoan)"  
    },
    {
        name: "Human-Human no mi: Onyudo",
        jname: "Hito-Hito no Mi",
        element : "Model: Onyudo",
        user: "User: Onimaru(Animal: komagitsune)",
        manga:"Manga Debut: Chapter 936",
        anime:"Anime Debut: Episode 932",
        Type:"(Mythical Zoan)"  
    },
    {
        name: "Dog-Dog Fruit: Nine Tailed Fox",
        jname: "Inu-Inu no Mi",
        element : "Model: Nine Tailed Fox",
        user: "User: Catarina Devon",
        manga:"Manga Debut: Chapter 575",
        anime:"Anime Debut: Episode 484",
        Type:"(Mythical Zoan)" 
    },
    {
        name: "Dog-Dog Fruit: Okuchi no Makami",
        jname: "Inu Inu no Mi",
        element : "Model: Okuchi no Makami",
        user: "User: Yamato",
        manga:"Manga Debut: Chapter 971",
        anime:"Anime Debut: Episode 972",
        Type:"(Mythical Zoan)" 
    },
    {
        name: "Dog-Dog Fruit: Bake-Danuki",
        jname: "Inu-Inu no Mi",
        element : "Model: Bake-Danuki",
        user: "User: Pato",
        manga:"Manga Debut: N/A",
        anime:"Game Debut: One Piece: Unlimited World Red",
        Type:"(Mythical Zoan)" 
    },
    {
        name: "Bird-Bird Fruit: Phoenix",
        jname: "Tori-Tori no Mi",
        element : "Model: Phoenix",
        user: "User: Marco",
        manga:"Manga Debut: Chapter 234",
        anime:"Anime Debut: Episode 151",
        Type:"(Mythical Zoan)" 
    },
    {
        name: "Bird-Bird Fruit: Nue",
        jname: "Tori-Tori no Mi",
        element : "Model: Nue",
        user: "User: Toratsugu",
        manga:"Manga Debut: One piece Art Nue",
        anime:"Anime Debut: N/A",
        Type:"(Mythical Zoan)" 
    },
    {
        name: "Fish-Fish Fruit: Azure Dragon",
        jname: "Inu-Inu no Mi",
        element : "Model: Azure Dragon",
        user: "User: Kaido(Deceased?)",
        manga:"Manga Debut: Chapter 795",
        anime:"Anime Debut: Episode 736",
        Type:"(Mythical Zoan)" 
    },
    {
        name: "Horse-Horse Fruit: Pegasus",
        jname: "Uma-Uma no Mi",
        element : "Model: Pegasus",
        user: "User: Stronger",
        manga:"Manga Debut: Chapter 223",
        anime:"Anime Debut: Episode 146",
        Type:"(Mythical Zoan)" 
    },
    {
        name: "Snake-Snake Fruit: Eight Headed Serpent",
        jname: "Hebi-Hebi no Mi",
        element : "Model: Eight Headed Serpent",
        user: "User: Kurozumi Orochi(Deceased)",
        manga:"Manga Debut: Chapter 927",
        anime:"Anime Debut: Episode 921",
        Type:"(Mythical Zoan)" 
    },
    {
        name: "Bat-Bat Fruit: Vampire",
        jname: "Batto-Batto no Mi",
        element : "Model: Vampire",
        user: "User: Patrick Redfield",
        manga:"Manga Debut: N/A",
        anime:"Game Debut: One Piece: Unlimited World Red",
        Type:"(Mythical Zoan)" 
    },

];
const zoanArtificial = [
    {
        name: "Fish-Fish Fruit: Azure Dragon",
        jname: "Uo Uo no Mi",
        element : "Model: Azure Dragon",
        user: "User: Kozuki Momonosuke",
        manga:"Manga Debut: Chapter 684",
        anime:"Anime Debut: Episode 609",
        Type:"(Artificial/Mythical Zoan)"  
    },
    {
        name: "Smile Fruit: (Unknown)",
        jname: "Smile no mi",
        element : "Model: (Unknown)",
        user: "User: Ginrummy(Deceased?)",
        manga:"Manga Debut: Chapter 795",
        anime:"Anime Debut: Episode 739",
    },
    {
        name: "Smile Fruit: Sheep",
        jname: "Smile no mi",
        element : "Model: Sheep",
        user: "User: Sheepshead(Deceased?)",
        manga:"Manga Debut: Chapter 795",
        anime:"Anime Debut: Episode 739",
    },
    {
        name: "Smile Fruit: Bat",
        jname: "Smile no mi",
        element : "Model: Bat",
        user: "User: Bat-Man",
        manga:"Manga Debut: Chapter 914",
        anime:"Anime Debut: Episode 900",
    },
    {
        name: "Smile Fruit: Gazelle",
        jname: "Smile no mi",
        element : "Model: Gazelle",
        user: "User: Gazelle-Man",
        manga:"Manga Debut: Chapter 914",
        anime:"Anime Debut: Episode 900",
    },
    {
        name: "Smile Fruit: Mouse",
        jname: "Smile no mi",
        element : "Model: Mouse",
        user: "User: Mouse-Man",
        manga:"Manga Debut: Chapter 915",
        anime:"Anime Debut: Episode 901",
    },
    {
        name: "Smile Fruit: Lion",
        jname: "Smile no mi",
        element : "Model: Lion",
        user: "User: Holdem",
        manga:"Manga Debut: Chapter 915",
        anime:"Anime Debut: Episode 901",
    },
    {
        name: "Smile Fruit: Horse",
        jname: "Smile no mi",
        element : "Model: Horse",
        user: "User: Speed",
        manga:"Manga Debut: Chapter 917",
        anime:"Anime Debut: Episode 904",
    },
    {
        name: "Smile Fruit: Horse",
        jname: "Smile no mi",
        element : "Model: Horse",
        user: "User: Fuga",
        manga:"Manga Debut: Chapter 991",
        anime:"Anime Debut: Episode 1055",
    },
    {
        name: "Smile Fruit: Snake",
        jname: "Smile no mi",
        element : "Model: Snake",
        user: "User: Sarahebi",
        manga:"Manga Debut: Chapter 919",
        anime:"Anime Debut: Episode 909",
    },
    {
        name: "Smile Fruit: Snake",
        jname: "Smile no mi",
        element : "Model: Snake",
        user: "User: Snake-Man",
        manga:"Manga Debut: Chapter 916",
        anime:"Anime Debut: Episode 904",
    },
    {
        name: "Smile Fruit: White Snake",
        jname: "Smile no mi",
        element : "Model: White Snake",
        user: "User: Tenjo-Sagari",
        manga:"Manga Debut: Chapter 980",
        anime:"Anime Debut: Episode 986",
    },
    {
        name: "Smile Fruit: Rattle Snake",
        jname: "Smile no mi",
        element : "Model: Rattle Snake",
        user: "User: Poker",
        manga:"Manga Debut: Chapter 997",
        anime:"Anime Debut: Episode 982",
    },
    {
        name: "Smile Fruit: Hognose Snake",
        jname: "Smile no mi",
        element : "Model: Hognose Snake",
        user: "User: Nure-Onna",
        manga:"Manga Debut: Chapter 998",
        anime:"Anime Debut: Episode 1013",
    },
    {
        name: "Smile Fruit: Rabbit",
        jname: "Smile no mi",
        element : "Model: Rabbit",
        user: "User: Rabbit-Man",
        manga:"Manga Debut: Chapter 916",
        anime:"Anime Debut: Episode 904",
    },
    {
        name: "Smile Fruit: Armadillo",
        jname: "Smile no mi",
        element : "Model: Armadillo",
        user: "User: Madillo-Man",
        manga:"Manga Debut: Chapter 939",
        anime:"Anime Debut: Episode 935",
    },
    {
        name: "Smile Fruit: Hippopotamus",
        jname: "Smile no mi",
        element : "Model: Hippopotamus",
        user: "User: Dobon",
        manga:"Manga Debut: Chapter 926",
        anime:"Anime Debut: Episode 919",
    },
    {
        name: "Smile Fruit: Ostrich",
        jname: "Smile no mi",
        element : "Model: Ostrich",
        user: "User: Dachoman",
        manga:"Manga Debut: Chapter 940",
        anime:"Anime Debut: Episode 937",
    },
    {
        name: "Smile Fruit: Alpaca",
        jname: "Smile no mi",
        element : "Model: Alpaca",
        user: "User: Alpaca-man",
        manga:"Manga Debut: Chapter 934",
        anime:"Anime Debut: Episode 929",
    },
    {
        name: "Smile Fruit: Scorpion",
        jname: "Smile no mi",
        element : "Model: Scorpion",
        user: "User: Daifugo",
        manga:"Manga Debut: Chapter 934",
        anime:"Anime Debut: Episode 928",
    },
    {
        name: "Smile Fruit: Elephant",
        jname: "Smile no mi",
        element : "Model: Elephant",
        user: "User: Babanuki",
        manga:"Manga Debut: Chapter 934",
        anime:"Anime Debut: Episode 930",
    },
    {
        name: "Smile Fruit: Monkey",
        jname: "Smile no mi",
        element : "Model: Monkey",
        user: "User: Solitaire",
        manga:"Manga Debut: Chapter 935",
        anime:"Anime Debut: Episode 930",
    },
    {
        name: "Smile Fruit: Flying Squirrel",
        jname: "Smile no mi",
        element : "Model: Flying Squirrel",
        user: "User: Bao Huang",
        manga:"Manga Debut: Chapter 979",
        anime:"Anime Debut: Episode 985",
    },
    {
        name: "Smile Fruit: Gorilla",
        jname: "Smile no mi",
        element : "Model: Gorilla",
        user: "User: Briscola",
        manga:"Manga Debut: Chapter 993",
        anime:"Anime Debut: Episode 982",
    },
    {
        name: "Smile Fruit: Gorilla",
        jname: "Smile no mi",
        element : "Model: Gorilla",
        user: "User: Mizerka",
        manga:"Manga Debut: Chapter 978",
        anime:"Anime Debut: Episode 982",
    },
    {
        name: "Smile Fruit: Chicken",
        jname: "Smile no mi",
        element : "Model: Chicken",
        user: "User: Fourtricks",
        manga:"Manga Debut: Chapter 994",
        anime:"Anime Debut: Episode 982",
    },
    {
        name: "Smile Fruit: Giraffe",
        jname: "Smile no mi",
        element : "Model: Giraffe",
        user: "User: Hamlet",
        manga:"Manga Debut: Chapter 994",
        anime:"Anime Debut: Episode 982",
    },
    {
        name: "Smile Fruit: Caiman",
        jname: "Smile no mi",
        element : "Model: Caiman",
        user: "User: Caiman-Lady",
        manga:"Manga Debut: Chapter 1004",
        anime:"Anime Debut: Episode 1020",
    },
    {
        name: "Smile Fruit: Pug",
        jname: "Smile no mi",
        element : "Model: Pug",
        user: "User: Wanyudo",
        manga:"Manga Debut: Chapter 1005",
        anime:"Anime Debut: Episode 1021",
    },
    {
        name: "Smile Fruit: Bird",
        jname: "Smile no mi",
        element : "Model: Bird",
        user: "User: Bird-man",
        manga:"Manga Debut: Chapter 975",
        anime:"Anime Debut: Episode 978",
    },
    {
        name: "Smile Fruit: Butterfly",
        jname: "Smile no mi",
        element : "Model: Butterfly",
        user: "User: Butterfly-lady",
        manga:"Manga Debut: Chapter 975",
        anime:"Anime Debut: Episode 978",
    },
    {
        name: "Smile Fruit: Stag Beetle",
        jname: "Smile no mi",
        element : "Model: Stag Beetle",
        user: "User: Stag Beetle-man",
        manga:"Manga Debut: Chapter 993",
        anime:"Anime Debut: Episode 1009",
    },
    {
        name: "Smile Fruit: Mantis",
        jname: "Smile no mi",
        element : "Model: Mantis",
        user: "User: Mantis-lady",
        manga:"Manga Debut: Chapter 993",
        anime:"Anime Debut: Episode 1009",
    },
    {
        name: "Smile Fruit: Tortoise",
        jname: "Smile no mi",
        element : "Model: Tortoise",
        user: "User: Tortoise-man",
        manga:"Manga Debut: Chapter 993",
        anime:"Anime Debut: Episode 1009",
    },
    {
        name: "Smile Fruit: Hedgehog",
        jname: "Smile no mi",
        element : "Model: Hedgehog",
        user: "User: Hedgehog-man",
        manga:"Manga Debut: Chapter 993",
        anime:"Anime Debut: Episode 1009",
    },
    {
        name: "Smile Fruit: Rhino",
        jname: "Smile no mi",
        element : "Model: Rhino",
        user: "User: Rhino-man",
        manga:"Manga Debut: Chapter 993",
        anime:"Anime Debut: Episode 1009",
    },
    {
        name: "Smile Fruit: Rhino Beetle",
        jname: "Smile no mi",
        element : "Model: Rhino Beetle",
        user: "User: Rhino Beetle-man",
        manga:"Manga Debut: Chapter 993",
        anime:"Anime Debut: Episode 1009",
    },
    {
        name: "Smile Fruit: Bear",
        jname: "Smile no mi",
        element : "Model: Bear",
        user: "User: Bear-man",
        manga:"Manga Debut: Non-Canon",
        anime:"Anime Debut: Episode 934",
    },
];

devilFruits.push(logia, parBody, parSub, parEnv, parPow, zoanNormal, zoanAnicent, zoanMythical, zoanArtificial);

export  {devilFruits, logia, parBody, parEnv, parPow, parSub, zoanAnicent, zoanArtificial, zoanMythical, zoanNormal};